stages:
  - test

variables:
  APPTAINER_VERSION: 1.4.3

regression-test-on-debian:
  stage: test
  image: ghcr.io/zhao-shihan/rgb-docker:mpich
  tags:
    - debian
  script:
    - . /enviroment
    #################################
    #        build-with-gcc         #
    #################################
    - mkdir build-with-gcc
    - cd build-with-gcc
    - cmake -G Ninja ../.. -DCMAKE_C_COMPILER=fastgcc -DCMAKE_CXX_COMPILER=fastg++ -DCMAKE_C_FLAGS='-Werror -march=x86-64-v2' -DCMAKE_CXX_FLAGS='-Werror -march=x86-64-v2'
    - ninja
    - cd ..
    #################################
    #        build-with-clang       #
    #################################
    - mkdir build-with-clang
    - cd build-with-clang
    - cmake -G Ninja ../.. -DCMAKE_C_COMPILER=fastclang -DCMAKE_CXX_COMPILER=fastclang++ -DCMAKE_C_FLAGS='-Werror -march=native' -DCMAKE_CXX_FLAGS='-Werror -march=native' -DMACE_FULL_UNITY_BUILD=ON
    - ninja
    - cd ..
    #################################
    #        test-with-gcc          #
    #################################
    - cd build-with-gcc
    - bash test/module_test.sh
    - cd ..
    #################################
    #        test-with-clang        #
    #################################
    - cd build-with-clang
    - bash test/module_test.sh
    - cd ..
  artifacts:
    paths: 
      - ci-work-dir/build-with-gcc/test
      - ci-work-dir/build-with-clang/test
    expire_in: "100 days"
