stages:
  - test

variables:
  IMAGE_VERSION: 25.10.16

regression-test-on-debian:
  stage: test
  image: ghcr.io/zhao-shihan/rgb-docker:${IMAGE_VERSION}-mpich
  tags:
    - debian
  script:
    - . /environment
    #################################
    #        build-with-gcc         #
    #################################
    - mkdir build-with-gcc
    - cd build-with-gcc
    - cmake -G Ninja .. -DCMAKE_C_COMPILER=gcc-opt -DCMAKE_C_FLAGS='-Werror -march=x86-64-v2' -DCMAKE_CXX_FLAGS='-Werror -march=x86-64-v2' -DCMAKE_BUILD_TYPE=Release
    - ninja
    - cd ..
    #################################
    #        build-with-clang       #
    #################################
    - mkdir build-with-clang
    - cd build-with-clang
    - cmake -G Ninja .. -DCMAKE_C_COMPILER=clang-opt -DCMAKE_CXX_COMPILER=clang++-opt -DCMAKE_C_FLAGS='-Werror -march=native' -DCMAKE_CXX_FLAGS='-Werror -march=native' -DMACE_FULL_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=Release
    - ninja
    - cd ..
    #################################
    #        test-with-gcc          #
    #################################
    - cd build-with-gcc
    - bash test/module_test.sh
    - cd ..
    #################################
    #        test-with-clang        #
    #################################
    - cd build-with-clang
    - bash test/module_test.sh
    - cd ..
  artifacts:
    paths: 
      - ci-work-dir/build-with-gcc/test
      - ci-work-dir/build-with-clang/test
    expire_in: "100 days"
