stages:
  - pre
  - build
  - test

get-apptainer:
  stage: pre
  tags:
    - debian
  script:
    - apt -y update
    - apt -y full-upgrade
    - apt -y install wget
    - wget https://github.com/apptainer/apptainer/releases/download/v1.4.3/apptainer_1.4.3-trixie+_amd64.deb -O apptainer.deb
    - apt -y install ./$_
    - rm $_
    
pull-image:
  stage: pre
  tags:
    - debian
  script:
    - mkdir build && cd $_
    - apptainer pull rgb.sif oras://ghcr.io/zhao-shihan/rgb:openmpi
    - chmod +x rgb.sif

build-mace:
  stage: build
  tags:
    - debian
  script:
    - cd build
    - ./rgb.sif cmake -G Ninja -DCMAKE_C_FLAGS='-march=native' -DCMAKE_CXX_FLAGS='-march=native' ..
    - ./rgb.sif ninja

test-mace:
  stage: test
  tags:
    - debian
  script:
    - bash build/test/module_test.sh


