stages:
  - pre
  - build
  - test

get-apptainer:
  stage: pre
  tags:
    - debian
  script:
    - apt -y update
    - apt -y full-upgrade
    - apt -y install wget
    - wget https://github.com/apptainer/apptainer/releases/download/v1.4.3/apptainer_1.4.3-trixie+_amd64.deb -O apptainer.deb
    - apt -y install ./apptainer.deb
    - rm ./apptainer.deb
    
pull-image:
  stage: pre
  tags:
    - debian
  script:
    - mkdir build && cd $_
    - apptainer pull rgb.sif oras://ghcr.io/zhao-shihan/rgb:openmpi
    - chmod +x rgb.sif

build-with-gcc:
  stage: build
  tags:
    - debian
  script:
    - cd build
    - ./rgb.sif cmake -G Ninja -DCMAKE_C_FLAGS='-Werror -march=native' -DCMAKE_CXX_FLAGS='-Werror -march=native' ..
    - ./rgb.sif ninja

test-mace:
  stage: test
  tags:
    - debian
  script:
  # Delete this line when 'mace_regression_data.root' is already download from cmake.
    - bash build/test/generate_regression_data.sh
    - bash build/test/module_test.sh
