name: Regression test (AMD64 GNU/Linux GCC)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-with-gcc:
    name: Test with GCC
    timeout-minutes: 180
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ghcr.io/zhao-shihan/rgb-docker:mpich
          - ghcr.io/zhao-shihan/rgb-docker:openmpi
    container: ${{ matrix.image }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          . /environment
          mkdir build && cd build
          cmake -G Ninja .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_C_FLAGS='-Werror -march=x86-64-v2' \
            -DCMAKE_CXX_FLAGS='-Werror -march=x86-64-v2'
          ninja

      - name: Run regression test
        run: |
          . /environment
          bash build/test/regression_test.bash

      - name: Restore regression report
        uses: actions/upload-artifact@v4
        with:
          name: test report of ${{ matrix.image }}
          path: |
            build/test/test_*/regression_report.root
          retention-days: 90
